##==============================================================================
## The Go-Back-N Protocol
##
## @description: Makefile for sender.java and receiver.java
## @author: Elisha Lai
## @version: 1.0 01/11/2016
##==============================================================================

all:
	@echo "Compiling..."
	javac *.java

.PHONY: clean

clean:
	@echo "Cleaning..."
	find . -name "*.class" -delete
